### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by yangzhengnan-le** [brnluiz/ocpp-server-tool#1]
how to use and test it

**Comment by brunoluiz** [comment]
This is just an initial version. In the following weeks I will refactor it, add an README and add more commands (atm it only accepts 3 commands: remotestart, remotestop and heartbeat).

**Comment by brunoluiz** [comment]
- Added a README explaining how to use it. 
- To test it you will need a charging station or a simulator. It is not that hard, as I am working now on this Charge Station firmware (but I can't open-source it). With Java is quite straight forward.
